export const DUMMY = 'DUMMY';
export const SECURITY_GROUP_FLAG = 'SECURITY_GROUP_FLAG';
export const SECURITY_GROUP_DATA = 'SECURITY_GROUP_DATA';
export const TICKERS_GRID_DATA = 'TICKERS_GRID_DATA';
export const FILTERS_SELECTED_DATA = 'FILTERS_SELECTED_DATA';
export const NEW_TICKERS_GRID_DATA = 'NEW_TICKERS_GRID_DATA';
export const DUMMY_API_DATA = 'DUMMY_API_DATA';
export const UPDATE_API_DATA = 'UPDATE_API_DATA';