/* mock data for the basic
table to display
*/

export const gridHeaders=[
    {headerName: 'Group Name',
    rowSpan: 2,
    colSpan:1,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
    showSortingIcon: false,
   },
    {headerName: 'LOB',
    rowSpan: 2,
    colSpan:1,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
    showSortingIcon: true,
   },
    {headerName: 'Include',
    rowSpan: 1,
    colSpan:4,
    showSortingIcon: false,
    headerStyle:{backgroundColor:'rgb(181,195,222)',textAlign:'center', borderRight:'1px solid #fff'},
},
    {headerName: 'Exclude',
    rowSpan: 1,
    colSpan:2,
    showSortingIcon: false,
    headerStyle:{backgroundColor:'rgb(181,195,222)',textAlign:'center'},
},
{headerName: 'Count of Securities',
rowSpan: 2,
colSpan:1,
showSortingIcon: true,
headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
},

    {headerName: 'Action',
    rowSpan: 2,
    colSpan:1,
    showSortingIcon: false,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
},

]
export const subHeaders = [
    {headerName: 'L1/L2',
    rowSpan: 2,
    colSpan:1,
    showSortingIcon: false,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
   },
    {headerName: 'Country of Origin',
    rowSpan: 2,
    colSpan:1,
    showSortingIcon: false,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
   },

    {headerName: 'Product Group',
    rowSpan: 1,
    colSpan:1,
    showSortingIcon: false,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
},
    {headerName: 'Securities',
    rowSpan: 1,
    colSpan:1,
    showSortingIcon: false,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
},
    {headerName: 'Product Group',
    rowSpan: 1,
    colSpan:1,
    showSortingIcon: false,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
},
    {headerName: 'Securities',
    rowSpan: 1,
    colSpan:1,
    showSortingIcon: false,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
}];

/* Sample Schema for the security group grid
   data
*/

export const SecurityGroupGridData={
    "data":[
        {
            "groupname":"on Hold CEF",
            "LOB":'bcs',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
        {
            "groupname":"group 1",
            "LOB":'CF2',
            "l1-l2":"L1=1",
            "countryToInclude":["US","France","UK"],
            "productGroupToInclude":"22",
            "tickersToInclude":["ABC","DEF"],
            "productsToExclude":"18",
            "tickersToExclude":["xyz","abd"],
            "countOfSecurities": 2
        },
    ]
}

/*
Table headers for the
security group details tickers
table
*/
export const tickersDetailsHeaders=[
    {headerName: 'Tickers',
    rowSpan: 1,
    colSpan:1,
    showSortingIcon: true,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
   },
    {headerName: 'ISIN',
    rowSpan: 1,
    colSpan:1,
    showSortingIcon: true,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
   },
    {headerName: 'CUSIP',
    rowSpan: 1,
    colSpan:1,
    showSortingIcon: true,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
   },
    {headerName: 'ML Securities #',
    rowSpan: 1,
    colSpan:1,
    showSortingIcon: true,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
   },
    {headerName: 'Security Type',
    rowSpan: 1,
    colSpan:1,
    showSortingIcon: true,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
   },
    {headerName: 'Country of Listing',
    rowSpan: 1,
    colSpan:1,
    showSortingIcon: true,
    headerStyle:{backgroundColor:'rgba(234,239,250,1)'},
   }];
   export const tickersViewData={
    "data":[
        {
            "ticker":"MSFT",
            "isin":'ABC1234',
            "cusip":"74589625",
            "ml_securities":"09879",
            "security_type": ['equity','options'],
            "country_listing": 'US'},
        {
            "ticker":"IBM",
            "isin":'ABC1234',
            "cusip":"74589625",
            "ml_securities":"09879",
            "security_type": ['equity','options'],
            "country_listing": 'US'},
        {
            "ticker":"TSLA",
            "isin":'ABC1234',
            "cusip":"74589625",
            "ml_securities":"09879",
            "security_type": ['equity','options'],
            "country_listing": 'US'},
        {
            "ticker":"QQQ",
            "isin":'ABC1234',
            "cusip":"74589625",
            "ml_securities":"09879",
            "security_type": ['equity','options'],
            "country_listing": 'US'},
        {
            "ticker":"GOOG",
            "isin":'ABC1234',
            "cusip":"74589625",
            "ml_securities":"09879",
            "security_type": ['equity','options'],
            "country_listing": 'US'},
    ]
};